# Generated by Django 5.2.14 on 2026-05-18 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Stok Kodu (SKU)')),
                ('name', models.CharField(max_length=300, verbose_name='Ürün Adı')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('unit', models.CharField(choices=[('adet', 'Adet'), ('m2', 'm²'), ('kg', 'Kilogram')], default='adet', max_length=10, verbose_name='Birim')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mevcut Miktar')),
                ('min_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Minimum Eşik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stok Kalemi',
                'verbose_name_plural': 'Stok Kalemleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('entry', 'Giriş'), ('exit', 'Çıkış')], max_length=10, verbose_name='İşlem Tipi')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miktar')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.stockitem', verbose_name='Stok Kalemi')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
