# Generated by Django 5.2.14 on 2026-05-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='usage_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Kullanım Yeri'),
        ),
    ]
