# Generated by Django 5.2.14 on 2026-05-18 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('todo', 'Yapılacak'), ('in_progress', 'Devam Ediyor'), ('done', 'Tamamlandı')], default='todo', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('medium', 'Orta'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='medium', max_length=20, verbose_name='Öncelik')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Son Tarih')),
                ('planned_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Planlanan Saat')),
                ('planned_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Planlanan Maliyet')),
                ('workflow_team_ids', models.JSONField(blank=True, default=list, verbose_name='İş Akışı Ekipleri (ID listesi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Kişi')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
            options={
                'verbose_name': 'Görev',
                'verbose_name_plural': 'Görevler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=100, verbose_name='Model Kodu')),
                ('dimension', models.CharField(blank=True, default='', max_length=100, verbose_name='Ölçü')),
                ('color', models.CharField(blank=True, default='', max_length=100, verbose_name='Renk')),
                ('blade_depth', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Bıçak Derinliği')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Sipariş Adedi')),
                ('qty_produced', models.PositiveIntegerField(default=0, verbose_name='Üretilen')),
                ('fire_qty', models.PositiveIntegerField(default=0, verbose_name='Fire Miktarı')),
                ('planning_mode', models.CharField(choices=[('manual', 'Manuel'), ('fixed', 'Sabit Süre')], default='manual', max_length=20, verbose_name='Planlama Modu')),
                ('unit_duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Birim Süre (dk)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='tasks.task', verbose_name='Görev')),
            ],
            options={
                'verbose_name': 'Üretim Kalemi',
                'verbose_name_plural': 'Üretim Kalemleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ekip Adı')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='Departman')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associates', models.ManyToManyField(blank=True, related_name='teams', to='accounts.teamassociate', verbose_name='Saha Çalışanları')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Üyeler')),
            ],
            options={
                'verbose_name': 'Ekip',
                'verbose_name_plural': 'Ekipler',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tasks', to='tasks.team', verbose_name='Mevcut Ekip'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.team', verbose_name='Ekip'),
        ),
    ]
