# Generated by Django 5.2.14 on 2026-05-18 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workflow_team_ids',
        ),
        migrations.AddField(
            model_name='productline',
            name='active_product_index',
            field=models.IntegerField(default=0, verbose_name='Aktif Aşama İndeksi'),
        ),
        migrations.AddField(
            model_name='productline',
            name='brief_intro',
            field=models.TextField(default='', max_length=600, verbose_name='Kısa Açıklama (1-600 Karakter)'),
        ),
        migrations.AddField(
            model_name='productline',
            name='fire_image',
            field=models.ImageField(blank=True, null=True, upload_to='scrap_images/', verbose_name='Fire Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='productline',
            name='fire_reason',
            field=models.TextField(blank=True, default='', verbose_name='Fire Sebebi'),
        ),
        migrations.AddField(
            model_name='productline',
            name='pending_approval',
            field=models.BooleanField(default=False, verbose_name='Onay Bekliyor'),
        ),
        migrations.AddField(
            model_name='productline',
            name='product_color_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Renk Kodu'),
        ),
        migrations.AddField(
            model_name='productline',
            name='stage_done',
            field=models.BooleanField(default=False, verbose_name='Üretim Tamamlandı'),
        ),
        migrations.AddField(
            model_name='productline',
            name='unit_type',
            field=models.CharField(choices=[('adet', 'Adet'), ('metre', 'Metre')], default='adet', max_length=20, verbose_name='Birim Tipi'),
        ),
        migrations.AddField(
            model_name='productline',
            name='variant',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Varyant'),
        ),
        migrations.AddField(
            model_name='productline',
            name='workflow_stage_targets',
            field=models.JSONField(blank=True, default=dict, verbose_name='Aşama Hedefleri (TeamID: Hedef Miktar)'),
        ),
        migrations.AddField(
            model_name='productline',
            name='workflow_team_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='İş Akışı Ekipleri (Sıralı ID Listesi)'),
        ),
        migrations.CreateModel(
            name='ProductLineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_produced_at_stage', models.PositiveIntegerField(default=0)),
                ('scrap_qty_at_stage', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='tasks.productline')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_histories', to='tasks.team')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üretim Geçmişi',
                'verbose_name_plural': 'Üretim Geçmişleri',
                'ordering': ['started_at'],
            },
        ),
    ]
