# Generated by Django 5.2.14 on 2026-05-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_current_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Ürün Kodu (Örn: AY-01)')),
                ('name', models.CharField(max_length=200, verbose_name='Model Adı')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Süre (dk)')),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='En (mm)')),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Boy (mm)')),
                ('additional_dimensions', models.CharField(blank=True, default='', max_length=300, verbose_name='Ek Ölçüler')),
                ('blade_min_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bıçak min (mm)')),
                ('blade_max_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Bıçak max (mm)')),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Kalınlık (mm)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Katalog Ürünü',
                'verbose_name_plural': 'Katalog Ürünleri',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='productline',
            name='image_base64',
            field=models.TextField(blank=True, default='', verbose_name='Kalem Görseli (Base64)'),
        ),
        migrations.AddField(
            model_name='productline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_lines', to='tasks.product', verbose_name='Katalog Ürünü'),
        ),
    ]
