# Generated by Django 5.2.14 on 2026-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_product_productline_image_base64_productline_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Şablon Adı')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='Şablon Adımları (TeamID listesi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İş Akışı Şablonu',
                'verbose_name_plural': 'İş Akışı Şablonları',
                'ordering': ['name'],
            },
        ),
    ]
