# Generated by Django 5.2.14 on 2026-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_workflowtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlinehistory',
            name='activity_notes',
            field=models.TextField(blank=True, default='', verbose_name='Ek Açıklamalar'),
        ),
        migrations.AddField(
            model_name='productlinehistory',
            name='scrap_location',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Fire Nerede Oluştu?'),
        ),
        migrations.AddField(
            model_name='productlinehistory',
            name='work_description',
            field=models.TextField(blank=True, default='', verbose_name='Yapılan İş Detayı'),
        ),
        migrations.AddField(
            model_name='productlinehistory',
            name='working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Çalışılan Saat'),
        ),
    ]
