# Generated by Django 5.2.14 on 2026-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_productlinehistory_activity_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlinehistory',
            name='giben_plate_size',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Kullanılan Tabaka Ölçüsü'),
        ),
        migrations.AddField(
            model_name='productlinehistory',
            name='pvc_color',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Renk'),
        ),
        migrations.AddField(
            model_name='productlinehistory',
            name='pvc_cut_size',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Kesim Ölçüsü'),
        ),
        migrations.AddField(
            model_name='productlinehistory',
            name='pvc_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Metre'),
        ),
        migrations.AddField(
            model_name='productlinehistory',
            name='pvc_roll_size',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Rulo Boy'),
        ),
    ]
