# Generated by Django 5.2.14 on 2026-05-21 20:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_productlinehistory_giben_plate_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(default=datetime.time(8, 30), verbose_name='Mesai Başlangıç Saati')),
                ('work_end_time', models.TimeField(default=datetime.time(18, 30), verbose_name='Mesai Bitiş Saati')),
                ('overtime_start_time', models.TimeField(blank=True, null=True, verbose_name='Fazla Mesai Başlangıç')),
                ('overtime_end_time', models.TimeField(blank=True, null=True, verbose_name='Fazla Mesai Bitiş')),
                ('work_days', models.CharField(default='0,1,2,3,4,5', max_length=50, verbose_name='Çalışma Günleri')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
            },
        ),
        migrations.AlterField(
            model_name='productlinehistory',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
