# Generated by Django 5.2.14 on 2026-05-22 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_systemsettings_lunch_break'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLineProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('qty_produced', models.PositiveIntegerField(default=0)),
                ('scrap_qty', models.PositiveIntegerField(default=0)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('work_description', models.TextField(blank=True, default='')),
                ('fire_reason', models.TextField(blank=True, default='')),
                ('scrap_location', models.CharField(blank=True, default='', max_length=200)),
                ('activity_notes', models.TextField(blank=True, default='')),
                ('pvc_color', models.CharField(blank=True, default='', max_length=100)),
                ('pvc_roll_size', models.CharField(blank=True, default='', max_length=100)),
                ('pvc_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pvc_cut_size', models.CharField(blank=True, default='', max_length=200)),
                ('giben_plate_size', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='tasks.productline')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='tasks.team')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Günlük Üretim Kaydı',
                'verbose_name_plural': 'Günlük Üretim Kayıtları',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
