# Generated by Django 5.2.14 on 2026-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_productlineproductionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Ürün Adı'),
        ),
    ]
